CREATE TABLE `activities` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '活动标题',
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '活动描述',
  `type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '活动类型',
  `start_time` datetime NOT NULL COMMENT '开始时间',
  `end_time` datetime NOT NULL COMMENT '结束时间',
  `location` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '活动地点',
  `quota` int NOT NULL COMMENT '招募人数',
  `registered_count` int DEFAULT '0' COMMENT '已报名人数',
  `organizer_id` int NOT NULL COMMENT '组织者ID',
  `organization_id` int NOT NULL COMMENT '所属组织ID',
  `status` enum('draft','recruiting','ongoing','completed','cancelled') COLLATE utf8mb4_unicode_ci DEFAULT 'draft' COMMENT '活动状态',
  `qr_code` text COLLATE utf8mb4_unicode_ci,
  `sign_out_qr_code` text COLLATE utf8mb4_unicode_ci COMMENT '签退二维码',
  `requirements` text COLLATE utf8mb4_unicode_ci COMMENT '报名要求',
  `images` json DEFAULT NULL COMMENT '活动图片URL列表',
  `is_long_term` tinyint(1) DEFAULT '0' COMMENT '是否为长期项目',
  `recurrence` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '重复规则（如：weekly, monthly）',
  `summary` text COLLATE utf8mb4_unicode_ci COMMENT '活动总结',
  `parent_activity_id` int DEFAULT NULL COMMENT '父活动ID，用于关联长期项目',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `organizer_id` (`organizer_id`),
  KEY `organization_id` (`organization_id`),
  KEY `parent_activity_id` (`parent_activity_id`),
  CONSTRAINT `activities_ibfk_91` FOREIGN KEY (`organizer_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `activities_ibfk_92` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `activities_ibfk_93` FOREIGN KEY (`parent_activity_id`) REFERENCES `activities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `activity_participants` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL COMMENT '用户ID',
  `activity_id` int NOT NULL COMMENT '活动ID',
  `status` enum('pending','approved','rejected') COLLATE utf8mb4_unicode_ci DEFAULT 'pending' COMMENT '报名状态',
  `sign_in_time` datetime DEFAULT NULL COMMENT '签到时间',
  `sign_out_time` datetime DEFAULT NULL COMMENT '签退时间',
  `duration` float DEFAULT NULL COMMENT '服务时长（小时）',
  `confirmed` tinyint(1) DEFAULT '0' COMMENT '服务记录是否已确认',
  `rating` int DEFAULT NULL COMMENT '评价评分（1-5分）',
  `comment` text COLLATE utf8mb4_unicode_ci COMMENT '评价内容',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `approved_by` int DEFAULT NULL COMMENT '审核人ID',
  `approved_at` datetime DEFAULT NULL COMMENT '审核时间',
  `approval_comment` text COLLATE utf8mb4_unicode_ci COMMENT '审核备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `activity_participants_activityId_userId_unique` (`user_id`,`activity_id`),
  UNIQUE KEY `activity_participants_activity_id_user_id` (`activity_id`,`user_id`),
  KEY `activity_participants_activity_id` (`activity_id`),
  KEY `activity_participants_user_id` (`user_id`),
  KEY `activity_participants_activity_id_status` (`activity_id`,`status`),
  KEY `activity_participants_activity_id_created_at` (`activity_id`,`created_at`),
  KEY `approved_by` (`approved_by`),
  CONSTRAINT `activity_participants_ibfk_65` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `activity_participants_ibfk_66` FOREIGN KEY (`activity_id`) REFERENCES `activities` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `activity_participants_ibfk_67` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=77 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `activity_trainings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `activity_id` int NOT NULL COMMENT '活动ID',
  `training_id` int NOT NULL COMMENT '培训ID',
  `is_required` tinyint(1) DEFAULT '0' COMMENT '是否为必填培训',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `activity_trainings_trainingId_activityId_unique` (`activity_id`,`training_id`),
  KEY `training_id` (`training_id`),
  CONSTRAINT `activity_trainings_ibfk_57` FOREIGN KEY (`activity_id`) REFERENCES `activities` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `activity_trainings_ibfk_58` FOREIGN KEY (`training_id`) REFERENCES `trainings` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `medals` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '勋章名称',
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '勋章描述',
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '勋章图片URL',
  `condition` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '获得条件',
  `category` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '勋章分类',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `name_2` (`name`),
  UNIQUE KEY `name_3` (`name`),
  UNIQUE KEY `name_4` (`name`),
  UNIQUE KEY `name_5` (`name`),
  UNIQUE KEY `name_6` (`name`),
  UNIQUE KEY `name_7` (`name`),
  UNIQUE KEY `name_8` (`name`),
  UNIQUE KEY `name_9` (`name`),
  UNIQUE KEY `name_10` (`name`),
  UNIQUE KEY `name_11` (`name`),
  UNIQUE KEY `name_12` (`name`),
  UNIQUE KEY `name_13` (`name`),
  UNIQUE KEY `name_14` (`name`),
  UNIQUE KEY `name_15` (`name`),
  UNIQUE KEY `name_16` (`name`),
  UNIQUE KEY `name_17` (`name`),
  UNIQUE KEY `name_18` (`name`),
  UNIQUE KEY `name_19` (`name`),
  UNIQUE KEY `name_20` (`name`),
  UNIQUE KEY `name_21` (`name`),
  UNIQUE KEY `name_22` (`name`),
  UNIQUE KEY `name_23` (`name`),
  UNIQUE KEY `name_24` (`name`),
  UNIQUE KEY `name_25` (`name`),
  UNIQUE KEY `name_26` (`name`),
  UNIQUE KEY `name_27` (`name`),
  UNIQUE KEY `name_28` (`name`),
  UNIQUE KEY `name_29` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `notifications` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL COMMENT '接收用户ID',
  `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '通知标题',
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '通知内容',
  `type` enum('activity','training','system','organization') COLLATE utf8mb4_unicode_ci DEFAULT 'system' COMMENT '通知类型：activity（活动相关）, training（培训相关）, system（系统通知）, organization（组织通知）',
  `related_id` int DEFAULT NULL COMMENT '关联ID（如活动ID、培训ID）',
  `is_read` tinyint(1) DEFAULT '0' COMMENT '是否已读',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `notifications_user_id_is_read` (`user_id`,`is_read`),
  KEY `notifications_user_id_created_at` (`user_id`,`created_at`),
  CONSTRAINT `notifications_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `organizations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '组织名称',
  `department` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '隶属部门',
  `contact` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '联系方式',
  `address` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '线下地点',
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '组织描述',
  `status` enum('pending','approved','rejected') COLLATE utf8mb4_unicode_ci DEFAULT 'pending' COMMENT '组织状态',
  `logo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '组织logo URL',
  `images` json DEFAULT NULL COMMENT '组织图片URL列表',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `name_2` (`name`),
  UNIQUE KEY `name_3` (`name`),
  UNIQUE KEY `name_4` (`name`),
  UNIQUE KEY `name_5` (`name`),
  UNIQUE KEY `name_6` (`name`),
  UNIQUE KEY `name_7` (`name`),
  UNIQUE KEY `name_8` (`name`),
  UNIQUE KEY `name_9` (`name`),
  UNIQUE KEY `name_10` (`name`),
  UNIQUE KEY `name_11` (`name`),
  UNIQUE KEY `name_12` (`name`),
  UNIQUE KEY `name_13` (`name`),
  UNIQUE KEY `name_14` (`name`),
  UNIQUE KEY `name_15` (`name`),
  UNIQUE KEY `name_16` (`name`),
  UNIQUE KEY `name_17` (`name`),
  UNIQUE KEY `name_18` (`name`),
  UNIQUE KEY `name_19` (`name`),
  UNIQUE KEY `name_20` (`name`),
  UNIQUE KEY `name_21` (`name`),
  UNIQUE KEY `name_22` (`name`),
  UNIQUE KEY `name_23` (`name`),
  UNIQUE KEY `name_24` (`name`),
  UNIQUE KEY `name_25` (`name`),
  UNIQUE KEY `name_26` (`name`),
  UNIQUE KEY `name_27` (`name`),
  UNIQUE KEY `name_28` (`name`),
  UNIQUE KEY `name_29` (`name`),
  UNIQUE KEY `name_30` (`name`),
  UNIQUE KEY `name_31` (`name`),
  UNIQUE KEY `name_32` (`name`),
  UNIQUE KEY `name_33` (`name`),
  UNIQUE KEY `name_34` (`name`),
  UNIQUE KEY `name_35` (`name`),
  UNIQUE KEY `name_36` (`name`),
  UNIQUE KEY `name_37` (`name`),
  UNIQUE KEY `name_38` (`name`),
  UNIQUE KEY `name_39` (`name`),
  UNIQUE KEY `name_40` (`name`),
  UNIQUE KEY `name_41` (`name`),
  UNIQUE KEY `name_42` (`name`),
  UNIQUE KEY `name_43` (`name`),
  UNIQUE KEY `name_44` (`name`),
  UNIQUE KEY `name_45` (`name`),
  UNIQUE KEY `name_46` (`name`),
  UNIQUE KEY `name_47` (`name`),
  UNIQUE KEY `name_48` (`name`),
  UNIQUE KEY `name_49` (`name`),
  UNIQUE KEY `name_50` (`name`),
  UNIQUE KEY `name_51` (`name`),
  UNIQUE KEY `name_52` (`name`),
  UNIQUE KEY `name_53` (`name`),
  UNIQUE KEY `name_54` (`name`),
  UNIQUE KEY `name_55` (`name`),
  UNIQUE KEY `name_56` (`name`),
  UNIQUE KEY `name_57` (`name`),
  UNIQUE KEY `name_58` (`name`),
  UNIQUE KEY `name_59` (`name`),
  UNIQUE KEY `name_60` (`name`),
  UNIQUE KEY `name_61` (`name`),
  UNIQUE KEY `name_62` (`name`),
  UNIQUE KEY `name_63` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `skills` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '技能名称',
  `description` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '技能描述',
  `category` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '技能分类',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `name_2` (`name`),
  UNIQUE KEY `name_3` (`name`),
  UNIQUE KEY `name_4` (`name`),
  UNIQUE KEY `name_5` (`name`),
  UNIQUE KEY `name_6` (`name`),
  UNIQUE KEY `name_7` (`name`),
  UNIQUE KEY `name_8` (`name`),
  UNIQUE KEY `name_9` (`name`),
  UNIQUE KEY `name_10` (`name`),
  UNIQUE KEY `name_11` (`name`),
  UNIQUE KEY `name_12` (`name`),
  UNIQUE KEY `name_13` (`name`),
  UNIQUE KEY `name_14` (`name`),
  UNIQUE KEY `name_15` (`name`),
  UNIQUE KEY `name_16` (`name`),
  UNIQUE KEY `name_17` (`name`),
  UNIQUE KEY `name_18` (`name`),
  UNIQUE KEY `name_19` (`name`),
  UNIQUE KEY `name_20` (`name`),
  UNIQUE KEY `name_21` (`name`),
  UNIQUE KEY `name_22` (`name`),
  UNIQUE KEY `name_23` (`name`),
  UNIQUE KEY `name_24` (`name`),
  UNIQUE KEY `name_25` (`name`),
  UNIQUE KEY `name_26` (`name`),
  UNIQUE KEY `name_27` (`name`),
  UNIQUE KEY `name_28` (`name`),
  UNIQUE KEY `name_29` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `training_participants` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL COMMENT '用户ID',
  `training_id` int NOT NULL COMMENT '培训ID',
  `status` enum('pending','approved','rejected','completed') COLLATE utf8mb4_unicode_ci DEFAULT 'pending' COMMENT '报名状态',
  `attendance` tinyint(1) DEFAULT '0' COMMENT '是否出席',
  `rating` int DEFAULT NULL COMMENT '评价评分（1-5分）',
  `comment` text COLLATE utf8mb4_unicode_ci COMMENT '评价内容',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `training_participants_trainingId_userId_unique` (`user_id`,`training_id`),
  KEY `training_id` (`training_id`),
  CONSTRAINT `training_participants_ibfk_45` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `training_participants_ibfk_46` FOREIGN KEY (`training_id`) REFERENCES `trainings` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `trainings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '课程标题',
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '课程描述',
  `type` enum('general','specialized') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '课程类型',
  `start_time` datetime NOT NULL COMMENT '开始时间',
  `end_time` datetime NOT NULL COMMENT '结束时间',
  `location` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '上课地点',
  `quota` int NOT NULL COMMENT '招募人数',
  `registered_count` int DEFAULT '0' COMMENT '已报名人数',
  `teacher` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '讲师',
  `organizer_id` int NOT NULL COMMENT '组织者ID',
  `organization_id` int NOT NULL COMMENT '所属组织ID',
  `status` enum('draft','recruiting','ongoing','completed','cancelled') COLLATE utf8mb4_unicode_ci DEFAULT 'draft' COMMENT '课程状态',
  `images` json DEFAULT NULL COMMENT '培训图片URL列表',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `organizer_id` (`organizer_id`),
  KEY `organization_id` (`organization_id`),
  CONSTRAINT `trainings_ibfk_61` FOREIGN KEY (`organizer_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `trainings_ibfk_62` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `user_medals` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL COMMENT '用户ID',
  `medal_id` int NOT NULL COMMENT '勋章ID',
  `obtained_at` datetime DEFAULT NULL COMMENT '获得时间',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_medals_medalId_userId_unique` (`user_id`,`medal_id`),
  KEY `medal_id` (`medal_id`),
  CONSTRAINT `user_medals_ibfk_57` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `user_medals_ibfk_58` FOREIGN KEY (`medal_id`) REFERENCES `medals` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `user_skills` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL COMMENT '用户ID',
  `skill_id` int NOT NULL COMMENT '技能ID',
  `proficiency` enum('beginner','intermediate','advanced','expert') COLLATE utf8mb4_unicode_ci DEFAULT 'beginner' COMMENT '熟练度：beginner（初级）, intermediate（中级）, advanced（高级）, expert（专家）',
  `years_of_experience` int DEFAULT NULL COMMENT '经验年限',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_skills_skillId_userId_unique` (`user_id`,`skill_id`),
  UNIQUE KEY `user_skills_user_id_skill_id` (`user_id`,`skill_id`),
  KEY `skill_id` (`skill_id`),
  CONSTRAINT `user_skills_ibfk_57` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `user_skills_ibfk_58` FOREIGN KEY (`skill_id`) REFERENCES `skills` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '姓名',
  `phone` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '手机号',
  `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '邮箱',
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '密码',
  `role` enum('volunteer','organizer','admin') COLLATE utf8mb4_unicode_ci DEFAULT 'volunteer' COMMENT '角色',
  `gender` enum('male','female','other') COLLATE utf8mb4_unicode_ci DEFAULT 'other' COMMENT '性别',
  `age` int DEFAULT NULL COMMENT '年龄',
  `organization_id` int DEFAULT NULL COMMENT '所属组织ID',
  `volunteer_hours` float DEFAULT '0' COMMENT '志愿时长',
  `avatar` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户头像URL',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `phone` (`phone`),
  UNIQUE KEY `email` (`email`),
  KEY `organization_id` (`organization_id`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=103 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

